### ISSUE TITLE
关于anchor 的设置？

### ISSUE THREAD

**Issue by ztyxd** [miemie2013/Keras-YOLOv4#1]
我的数据集中目标普遍偏小，是用默认的anchor，还是自己用kmeans从新聚类?

聚类出来的结果是[11, 24],[12, 11], [15, 23], [16, 40], [25 , 16][28, 58],[44, 24], [59,113], [102, 44]

目前我是使用了聚类的结果，但是效果很差。
所以想请教你一下

**Comment by miemie2013** [comment]
3个输出层的感受野是固定不变的。其实你可以试试默认的。我也不知道。

**Comment by miemie2013** [comment]
> 我的数据集中目标普遍偏小，是用默认的anchor，还是自己用kmeans从新聚类?
> 
> 聚类出来的结果是[11, 24],[12, 11], [15, 23], [16, 40], [25 , 16][28, 58],[44, 24], [59,113], [102, 44]
> 
> 目前我是使用了聚类的结果，但是效果很差。
> 所以想请教你一下

3个输出层的感受野是固定不变的。其实你可以试试默认的。我也不知道。

**Comment by ztyxd** [comment]
@miemie2013 好的

**Comment by xliu79** [comment]
我的也是目标很小，最后用的Retinanet。

**Comment by ztyxd** [comment]
@xliu79  好的，谢谢
