### ISSUE TITLE
能否给个通用的数据处理？

### ISSUE THREAD

**Issue by guangqianqin** [miemie2013/Keras-YOLOv4#3]
![image](https://user-images.githubusercontent.com/28343661/83348991-c460f600-a363-11ea-897b-0b1e3794db80.png)
都是这样就行，为啥训练数据和测试数据还要用不同的方式啊

**Comment by miemie2013** [comment]
> ![image](https://user-images.githubusercontent.com/28343661/83348991-c460f600-a363-11ea-897b-0b1e3794db80.png)
> 都是这样就行，为啥训练数据和测试数据还要用不同的方式啊

好的，在统一
