### ISSUE TITLE
Using keras custom trained model In video?

### ISSUE THREAD

**Issue by prateek09101996** [miemie2013/Keras-YOLOv4#32]
Hi, I am a noob in computer vision. I was able to follow the author and train my custom dataset in yolov4 Keras. The final map value is great and its accuracy in images is great as well. But how to apply detection in video files? 
Can anyone provide me some insight?

**Comment by miemie2013** [comment]
> Hi, I am a noob in computer vision. I was able to follow the author and train my custom dataset in yolov4 Keras. The final map value is great and its accuracy in images is great as well. But how to apply detection in video files?
> Can anyone provide me some insight?

demo_video.py
