### ISSUE TITLE
Downloading the pytorch model yolov4.pt is not possible for people from the UK

### ISSUE THREAD

**Issue by MjdMahasneh** [miemie2013/Keras-YOLOv4#43]
Since the website requires registration to download the file and its also difficult to interact with since its a different language. It would really be nice to provide the file maybe on google drive to something similar

**Comment by miemie2013** [comment]
> Since the website requires registration to download the file and its also difficult to interact with since its a different language. It would really be nice to provide the file maybe on google drive to something similar

Try PPYOLO.

https://github.com/miemie2013/Keras-PPYOLO-YOLOv4

wwget https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_2x.pdparams

I hope you can visit baidu.I can't visit google!

**Comment by miemie2013** [comment]
> Since the website requires registration to download the file and its also difficult to interact with since its a different language. It would really be nice to provide the file maybe on google drive to something similar

Try PPYOLO.

https://github.com/miemie2013/Keras-PPYOLO-YOLOv4

wget https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_2x.pdparams

I hope you can visit baidu.I can't visit google!

**Comment by MjdMahasneh** [comment]
Thank you.
